import type { Database } from '../types/database.types'
import type { ActivityRecord, EngagementRecord, OpportunityRecord, OrganizationRecord, PaymentRecord, PaymentRequestRecord, PersonRecord, PrestationRecord, ServiceRecord } from './domain'

type Tables = Database['public']['Tables']
const optional = <T>(value: T | null | undefined) => value == null ? undefined : value
const nullable = <T>(value: T | null | undefined) => value ?? null
export const normalizeEmail = (value: string) => value.trim().toLocaleLowerCase('es-CL')
export const durationBetween = (start?: string | null, end?: string | null) => start && end ? Math.max(0, Math.round((Date.parse(end) - Date.parse(start)) / 60000)) : undefined

export const personMapper = {
  fromRow: (row: Tables['accounts']['Row']): PersonRecord => ({ id: row.id, workspaceId: row.workspace_id, displayName: row.display_name, firstName: optional(row.first_name), lastName: optional(row.last_name), email: optional(row.email), organizationId: optional(row.organization_id), role: optional(row.role), phone: optional(row.phone), taxId: optional(row.tax_id), status: row.status, notes: optional(row.notes), archivedAt: optional(row.archived_at), createdAt: row.created_at, updatedAt: row.updated_at }),
  toInsert: (record: Omit<PersonRecord, 'id'|'createdAt'|'updatedAt'>): Tables['accounts']['Insert'] => ({ workspace_id: record.workspaceId, account_type: 'person', display_name: record.displayName, first_name: nullable(record.firstName), last_name: nullable(record.lastName), email: record.email ? normalizeEmail(record.email) : null, organization_id: nullable(record.organizationId), role: nullable(record.role), phone: nullable(record.phone), tax_id: nullable(record.taxId), status: record.status, notes: nullable(record.notes), archived_at: nullable(record.archivedAt) }),
}

export const organizationMapper = {
  fromRow: (row: Tables['organizations']['Row']): OrganizationRecord => ({ id: row.id, workspaceId: row.workspace_id, name: row.name, legalName: optional(row.legal_name), taxId: optional(row.tax_id), email: optional(row.email), phone: optional(row.phone), website: optional(row.website), businessActivity: optional(row.business_activity), address: optional(row.address), commune: optional(row.commune), city: optional(row.city), region: optional(row.region), notes: optional(row.notes), archivedAt: optional(row.archived_at), createdAt: row.created_at, updatedAt: row.updated_at }),
  toInsert: (record: Omit<OrganizationRecord, 'id'|'createdAt'|'updatedAt'>): Tables['organizations']['Insert'] => ({ workspace_id: record.workspaceId, name: record.name, normalized_name: record.name.trim().toLocaleLowerCase('es-CL').replace(/\s+/g,' '), legal_name: nullable(record.legalName), tax_id: nullable(record.taxId), email: nullable(record.email), phone: nullable(record.phone), website: nullable(record.website), business_activity: nullable(record.businessActivity), address: nullable(record.address), commune: nullable(record.commune), city: nullable(record.city), region: nullable(record.region), notes: nullable(record.notes), archived_at: nullable(record.archivedAt) }),
}

export const opportunityMapper = { fromRow: (r: Tables['opportunities']['Row']): OpportunityRecord => ({ id:r.id,workspaceId:r.workspace_id,personId:r.account_id,name:r.name,amount:optional(r.estimated_amount),expectedCloseDate:optional(r.expected_close_date),stage:r.stage,status:r.status,notes:optional(r.notes),wonAt:optional(r.won_at),lostAt:optional(r.lost_at),lostReason:optional(r.lost_reason),createdAt:r.created_at,updatedAt:r.updated_at }) }
export const engagementMapper = { fromRow: (r: Tables['engagements']['Row']): EngagementRecord => ({ id:r.id,workspaceId:r.workspace_id,personId:r.account_id,opportunityId:optional(r.opportunity_id),name:r.name,type:r.engagement_type,status:r.status,billingType:r.billing_type,amount:optional(r.agreed_amount),startDate:optional(r.start_date),endDate:optional(r.end_date),notes:optional(r.notes),createdAt:r.created_at,updatedAt:r.updated_at }) }
export const prestationMapper = { fromRow: (r: Tables['prestations']['Row']): PrestationRecord => ({ id:r.id,workspaceId:r.workspace_id,personId:r.account_id,engagementId:optional(r.engagement_id),opportunityId:optional(r.opportunity_id),serviceId:optional(r.service_id),name:r.name,description:optional(r.description),scheduledStart:optional(r.scheduled_start),scheduledEnd:optional(r.scheduled_end),durationMinutes:durationBetween(r.scheduled_start,r.scheduled_end),status:r.status,unitPrice:r.unit_price,quantity:r.quantity,totalAmount:r.total_amount,followUpNote:optional(r.follow_up_note),completedAt:optional(r.completed_at),createdAt:r.created_at,updatedAt:r.updated_at }) }
export const activityMapper = { fromRow: (r: Tables['activities']['Row']): ActivityRecord => ({ id:r.id,workspaceId:r.workspace_id,personId:r.account_id,prestationId:optional(r.prestation_id),engagementId:optional(r.engagement_id),opportunityId:optional(r.opportunity_id),type:r.activity_type,title:r.title,description:optional(r.description),status:r.status,source:optional(r.source),scheduledAt:optional(r.scheduled_at),completedAt:optional(r.completed_at),createdAt:r.created_at,updatedAt:r.updated_at }) }
export const paymentRequestMapper = { fromRow: (r: Tables['payment_requests']['Row']): PaymentRequestRecord => ({ id:r.id,workspaceId:r.workspace_id,personId:r.account_id,parentRequestId:optional(r.parent_request_id),originPrestationId:optional(r.origin_prestation_id),originEngagementId:optional(r.origin_engagement_id),originOpportunityId:optional(r.origin_opportunity_id),status:r.status,amount:r.amount,currencyCode:r.currency_code,dueDate:optional(r.due_date),note:optional(r.notes),waivedAmount:r.waived_amount,waiverReason:optional(r.waiver_reason),waivedAt:optional(r.waived_at),waivedBy:optional(r.waived_by),createdAt:r.created_at,updatedAt:r.updated_at }) }
export const paymentMapper = { fromRow: (r: Tables['payments']['Row']): PaymentRecord => ({ id:r.id,workspaceId:r.workspace_id,personId:r.account_id,amount:r.amount,currencyCode:r.currency_code,paymentDate:optional(r.payment_date),method:optional(r.payment_method),reference:optional(r.reference),status:r.status,notes:optional(r.notes),voidedAt:optional(r.voided_at),voidedBy:optional(r.voided_by),voidReason:optional(r.void_reason),createdAt:r.created_at,updatedAt:r.updated_at }) }
export const serviceMapper = { fromRow: (r: Tables['services']['Row']): ServiceRecord => ({ id:r.id,workspaceId:r.workspace_id,name:r.name,description:optional(r.description),defaultDurationMinutes:optional(r.default_duration_minutes),defaultPrice:optional(r.default_price),active:r.active,createdAt:r.created_at,updatedAt:r.updated_at }) }
